name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Change this to your primary branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Site
        run: hugo --minify

      - name: Deploy to Netlify
        run: |
          curl -X POST -d {} https://api.netlify.com/build_hooks/https://api.netlify.com/build_hooks/662731eeada07f415bec248e
        env:
          YOUR_BUILD_HOOK_ID: ${{ secrets.662731eeada07f415bec248e }}
